# Generated by Django 5.2.6 on 2025-09-27 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_intents', to='magda_app.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
