# Generated by Django 5.2.7 on 2025-11-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bienvenue', max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/MP4 URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu d’accueil',
                'verbose_name_plural': 'Contenu d’accueil',
            },
        ),
    ]
