# Generated by Django 5.2.7 on 2025-11-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0003_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fleur.slot'),
        ),
    ]
