# Generated by Django 5.2.7 on 2025-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0005_order_quantity_order_vended_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='relay_channel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
